import "./globals.css";
import { Inter } from "next/font/google";
// import SnackbarAlert from '@/components/control/SnackbarAlert'
import { Providers } from "@/redux/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Demo App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        <link rel='icon' href='/pf3.ico'/>
      </head>
      <body className={inter.className}>
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
